apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-trivy-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "*"
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - "*"
